apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q15b75oop-nodejs
  janus-idp.io/tekton: q15b75oop-nodejs
  backstage.io/kubernetes-id: q15b75oop-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q15b75oop-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
