apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q15b75oop-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q15b75oop-nodejs 
  name: q15b75oop-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: q15b75oop-nodejs 
